import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { kernoPalette } from "@kerno/brand";
import "@kerno/brand/tokens.css";
import "./styles.css";

type Replay = any;
type Benchmark = any;
type Tab = "Home" | "Context" | "Routing" | "Timeline" | "Comparison" | "Limits";
type Theme = "light" | "dark";
type ProductState = "first-launch" | "no-repository" | "indexing" | "repository-ready" | "task-received" | "capsule-generated" | "context-expanded" | "route-selected" | "orchestration-running" | "test-failed" | "test-passed" | "context-invalidated" | "run-completed" | "baseline-available" | "recoverable-error" | "unrecoverable-error";

const tabs: Tab[] = ["Home", "Context", "Routing", "Timeline", "Comparison", "Limits"];
const states: Array<{ id: ProductState; label: string }> = [
  { id: "first-launch", label: "First launch" }, { id: "no-repository", label: "No repository" }, { id: "indexing", label: "Indexing" },
  { id: "repository-ready", label: "Repository ready" }, { id: "task-received", label: "Task received" }, { id: "capsule-generated", label: "Capsule generated" },
  { id: "context-expanded", label: "Context expanded" }, { id: "route-selected", label: "Route selected" }, { id: "orchestration-running", label: "Orchestration running" },
  { id: "test-failed", label: "Test failed" }, { id: "test-passed", label: "Test passed" }, { id: "context-invalidated", label: "Context invalidated" },
  { id: "run-completed", label: "Run completed" }, { id: "baseline-available", label: "Baseline comparison" }, { id: "recoverable-error", label: "Recoverable error" }, { id: "unrecoverable-error", label: "Unrecoverable error" }
];
const fmt = (value: unknown) => value === null || value === undefined ? "Unavailable" : typeof value === "boolean" ? value ? "Yes" : "No" : String(value);
const short = (value?: string | null) => value ? value.slice(0, 10) : "unborn";
const human = (value: string) => value.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replaceAll(/[-_.]/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const time = (value?: string) => value ? new Date(value).toLocaleString() : "Unavailable";
const initialTheme = (): Theme => {
  const stored = window.localStorage.getItem("kerno-theme");
  if (stored === "light" || stored === "dark") return stored;
  return window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
};

function App() {
  const [data, setData] = useState<Replay>(); const [benchmark, setBenchmark] = useState<Benchmark | null>(null); const [error, setError] = useState("");
  const [runtimeEvidence, setRuntimeEvidence] = useState<any>(null);
  const [tab, setTab] = useState<Tab>("Home"); const [selected, setSelected] = useState<any>();
  const [theme, setTheme] = useState<Theme>(initialTheme);
  const initialState = (new URLSearchParams(window.location.search).get("state") as ProductState | null) ?? "run-completed";
  const [productState, setProductState] = useState<ProductState>(states.some((state) => state.id === initialState) ? initialState : "run-completed");
  useEffect(() => {
    fetch("/replay.json").then((response) => { if (!response.ok) throw new Error("Replay artifact is unavailable. Run npm run demo:record."); return response.json(); }).then(setData).catch((reason) => setError(reason.message));
    fetch("/benchmark.json").then((response) => response.ok ? response.json() : null).then(setBenchmark).catch(() => setBenchmark(null));
    fetch("/runtime-evidence.json").then((response) => response.ok ? response.json() : null).then(setRuntimeEvidence).catch(() => setRuntimeEvidence(null));
  }, []);
  useEffect(() => { if (data?.initialCapsule?.items?.length && !selected) setSelected(data.initialCapsule.items[0]); }, [data, selected]);
  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    window.localStorage.setItem("kerno-theme", theme);
    document.querySelector('meta[name="theme-color"]')?.setAttribute("content", theme === "dark" ? kernoPalette.graphite[950] : kernoPalette.ivory);
  }, [theme]);
  if (error) return <StateScreen state="unrecoverable-error" onContinue={() => window.location.reload()} detail={error}/>;
  if (!data) return <StateScreen state="indexing" detail="Loading the signed replay and verifying its evidence envelope."/>;
  const previewOnly = ["first-launch", "no-repository", "indexing", "recoverable-error", "unrecoverable-error"].includes(productState);
  const previewDetail = productState === "recoverable-error" ? "The repository changed while indexing. Re-indexing can recover safely." : productState === "unrecoverable-error" ? "The local database failed its integrity check. Source files were not changed." : undefined;
  return <div className="shell">
    <a className="skip" href="#content">Skip to content</a>
    <Header data={data} theme={theme} onThemeChange={() => setTheme(theme === "light" ? "dark" : "light")}/>
    <div className="control-bar">
      <nav className="tabs" aria-label="Kerno views">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} aria-current={tab === item ? "page" : undefined} onClick={() => setTab(item)}>{item}</button>)}</nav>
      <label className="state-picker"><span>Judge state tour</span><select value={productState} onChange={(event) => setProductState(event.target.value as ProductState)}>{states.map((state) => <option key={state.id} value={state.id}>{state.label}</option>)}</select></label>
    </div>
    {previewOnly ? <StateScreen state={productState} onContinue={() => setProductState("run-completed")} {...(previewDetail ? { detail: previewDetail } : {})}/> : <main id="content">
      <TruthStrip state={productState} data={data} benchmark={benchmark}/>
      {tab === "Home" && <Home data={data} state={productState}/>}
      {tab === "Context" && <Context data={data} selected={selected} setSelected={setSelected}/>}
      {tab === "Routing" && <Routing data={data} runtimeEvidence={runtimeEvidence}/>}
      {tab === "Timeline" && <Timeline data={data}/>}
      {tab === "Comparison" && <Comparison data={data} benchmark={benchmark}/>}
      {tab === "Limits" && <Limits data={data} benchmark={benchmark}/>}
    </main>}
    <footer><span>Kerno 0.1.0</span><span>Local-first · telemetry off · source remains local</span><span>Recorded {time(data.recordedAt)}</span></footer>
  </div>;
}

function Header({ data, theme, onThemeChange }: { data: Replay; theme: Theme; onThemeChange: () => void }) {
  const repo = data.repository;
  return <header className="masthead"><a className="brand" href="#content" aria-label="Skip to Kerno content"><span className="brand-symbol" aria-hidden="true"><img className="brand-symbol-light" src="/brand/context-core-primary-light.svg" alt=""/><img className="brand-symbol-dark" src="/brand/context-core-primary-dark.svg" alt=""/></span><span>Kerno</span></a><div className="truth-banner"><span className="status-dot"/><span>{data.label}</span><small>artifact {short(data.artifactHash)}</small></div><div className="header-tools"><div className="repo-lockup"><b>{repo.name ?? "relaycart-ts"}</b><span>{repo.branch ?? "detached"} · {short(repo.head)}</span></div><button className="theme-toggle" type="button" aria-label={`Switch to ${theme === "light" ? "dark" : "light"} theme`} aria-pressed={theme === "dark"} onClick={onThemeChange}><span aria-hidden="true">{theme === "light" ? "◐" : "◑"}</span><span className="theme-label">{theme}</span></button></div></header>;
}

function TruthStrip({ state, data, benchmark }: { state: ProductState; data: Replay; benchmark: Benchmark | null }) {
  const tone = state.includes("failed") || state.includes("error") ? "danger" : state === "test-passed" ? "success" : state.includes("running") || state === "indexing" || state === "route-selected" ? "active" : state.includes("invalidated") ? "warning" : state === "context-expanded" ? "expansion-state" : state === "run-completed" ? "complete" : "neutral";
  return <section className={`truth-strip ${tone}`} aria-live="polite"><div><span className="eyebrow">Current product state</span><strong>{states.find((item) => item.id === state)?.label}</strong></div><p>{state === "baseline-available" ? benchmark?.comparisons?.some((comparison: any) => comparison.fairness?.passed) ? "A fair recorded pair is available." : "The comparison surface is ready, but no fair recorded pair exists yet." : state === "orchestration-running" ? "Preview only: a live run would execute a separate Codex phase thread with an explicit requested route." : state === "context-invalidated" ? `${data.invalidation.changedFiles.join(", ")} no longer matches the original evidence hash.` : "This state is backed by the canonical proof loop or clearly labeled as a product-state preview."}</p><span className="truth-kind">{["run-completed", "test-passed", "test-failed", "context-expanded", "context-invalidated"].includes(state) ? "RECORDED EVIDENCE" : "STATE PREVIEW"}</span></section>;
}

function StateScreen({ state, detail, onContinue }: { state: ProductState; detail?: string; onContinue?: () => void }) {
  const content: Record<string, { eyebrow: string; title: string; body: string; action?: string }> = {
    "first-launch": { eyebrow: "First launch", title: "Start with one repository, not a cloud account.", body: "Kerno stores repository intelligence locally. Index a fixture or connect the current trusted workspace.", action: "View recorded proof" },
    "no-repository": { eyebrow: "Repository required", title: "Nothing is indexed yet.", body: "Run kerno index from a trusted repository. Ignored files, symlinks, binaries, and oversized files stay out.", action: "View sample repository" },
    indexing: { eyebrow: "Indexing in progress", title: "Building repository evidence.", body: "Kerno is hashing changed files, extracting symbols, resolving imports, and retaining unchanged snapshots." },
    "recoverable-error": { eyebrow: "Recoverable error", title: "The snapshot changed during indexing.", body: "No source was modified. Re-index the current worktree to create a fresh, compatible snapshot.", action: "Return to recorded run" },
    "unrecoverable-error": { eyebrow: "Storage integrity failure", title: "Kerno stopped before trusting corrupt state.", body: "Export or remove the marked local data directory, then rebuild the index. Repository source remains untouched.", action: "Retry loading" }
  };
  const item = content[state] ?? { eyebrow: "Product state", title: human(state), body: detail ?? "This state is represented by Kerno’s run event model." };
  return <main id="content" className={`state-screen ${state}`} role={state.includes("error") ? "alert" : "status"} aria-busy={state === "indexing"}><div className="state-index">K / {String(states.findIndex((candidate) => candidate.id === state) + 1).padStart(2, "0")}</div><section><p className="eyebrow">{item.eyebrow}</p><h1>{item.title}</h1><p>{detail ?? item.body}</p>{onContinue && item.action ? <button className="text-action" onClick={onContinue}>{item.action} →</button> : null}</section><aside><span>{state === "indexing" ? "WORKING" : state.includes("error") ? "ACTION REQUIRED" : "LOCAL-FIRST"}</span><div className={state === "indexing" ? "loader" : "state-rule"}/></aside></main>;
}

function Home({ data, state }: { data: Replay; state: ProductState }) {
  const repo = data.repository; const task = data.task; const lifecycle = ["repository-ready", "task-received", "capsule-generated", "context-expanded", "route-selected", "orchestration-running", "test-failed", "test-passed", "context-invalidated", "run-completed"];
  const recorded = new Set(["repository-ready", "task-received", "capsule-generated", "context-expanded", "route-selected", "test-failed", "test-passed", "context-invalidated", "run-completed"]);
  return <section className="workspace"><div className="home-hero"><div><p className="eyebrow">Repository overview / {task.intent}</p><h1>Exactly-once refunds,<br/><em>proved from evidence.</em></h1></div><p className="task-copy">{task.taskText}</p><Outcome data={data}/></div>
    <section className="repository-ledger"><div className="ledger-title"><p className="eyebrow">Current identity</p><h2>{repo.name ?? "relaycart-ts"}</h2><code>{repo.branch ?? "detached"} / {short(repo.head)}</code></div><Metric n={repo.files} label="Files indexed"/><Metric n={repo.symbols} label="Symbols"/><Metric n={repo.memoryCount ?? 0} label="Verified memories"/><Metric n={repo.invalidationCount ?? 0} label="Invalidations"/></section>
    <div className="home-grid"><section className="wide panel"><div className="section-heading"><div><p className="eyebrow">Index state</p><h2>Fresh against the recorded worktree</h2></div><TruthPill kind="measured">Measured</TruthPill></div><dl className="identity"><Row label="Branch / commit" value={`${repo.branch ?? "detached"} / ${fmt(repo.head)}`}/><Row label="Last index" value={time(repo.indexFreshness)}/><Row label="Dirty worktree" value={fmt(repo.dirty)}/><Row label="Unchanged files reparsed" value={fmt(repo.unchangedReparsed)}/></dl><h3>Language breakdown</h3><div className="language-list">{Object.entries(repo.languageBreakdown ?? {}).map(([language, count]) => <div key={language}><span>{human(language)}</span><b>{String(count)}</b></div>)}</div></section>
      <section className="proof-sequence panel"><p className="eyebrow">Run state sequence</p><ol>{lifecycle.map((item, index) => { const reached = lifecycle.indexOf(state) >= index || state === "run-completed"; const observed = recorded.has(item); return <li key={item} className={observed && reached ? "done" : "pending"}><span>{String(index + 1).padStart(2, "0")}</span><b>{human(item)}{!observed ? <small> · not observed in replay</small> : null}</b></li>; })}</ol></section></div></section>;
}

function Context({ data, selected, setSelected }: { data: Replay; selected: any; setSelected: (item: any) => void }) {
  const capsule = data.initialCapsule; const child = data.childCapsule;
  return <section className="workspace"><PageIntro eyebrow="Context capsule" title="Small enough to inspect. Complete enough to challenge." body={`${capsule.estimatedTokens} estimated tokens selected within a ${capsule.budgetTokens}-token budget.`}/><div className="context-grid"><section className="capsule-panel panel"><div className="section-heading"><div><p className="eyebrow">Selected evidence</p><h2>{capsule.items.length} ranked items</h2></div><TruthPill kind="estimate">Estimate</TruthPill></div><div className="capsule-list">{capsule.items.map((item: any, index: number) => <button key={item.id} className={`capsule-row ${selected?.id === item.id ? "selected" : ""}`} onClick={() => setSelected(item)}><span className="rank">{String(index + 1).padStart(2, "0")}</span><span className="file"><b>{item.locator.symbol ?? item.locator.path.split("/").at(-1)}</b><small>{item.locator.path}</small></span><span className="score">{item.score.toFixed(3)}<small>context value</small></span><span className="tokens">{item.estimatedTokens}<small>token est.</small></span></button>)}</div><div className="expansion"><span className="expansion-icon">↳</span><div><p className="eyebrow">Expansion 01 / test evidence</p><b>{child.items.map((item: any) => item.locator.path).join(", ")}</b><small>Failing test named TransactionBoundary; +{child.estimatedTokens} estimated tokens.</small></div></div></section><Why item={selected}/></div>
    <section className="excluded panel"><div><p className="eyebrow">Excluded candidates</p><h2>{capsule.excluded.length} items held outside the initial budget</h2></div><ul>{capsule.excluded.slice(0, 8).map((item: any) => <li key={item.path}><code>{item.path}</code><span>{item.score.toFixed(3)}</span><p>{item.reason}</p></li>)}</ul></section></section>;
}

function Why({ item }: { item: any }) { if (!item) return null; return <aside className="why panel"><p className="eyebrow">Why included</p><h2>{item.locator.path.split("/").at(-1)}</h2><p className="reason">{item.reason}</p><dl><Row label="Freshness" value={`${Math.round(item.freshness * 100)}% · hash matched`}/><Row label="Confidence" value={`${Math.round(item.confidence * 100)}% · ${item.provenance?.[0]?.note?.split(";")[0]}`}/><Row label="Trust" value={item.trust}/><Row label="Provenance" value={item.provenance?.map((source: any) => source.id).join(", ")}/></dl><h3>Score composition</h3><div className="signals">{Object.entries(item.scoreBreakdown).filter(([key]) => key !== "tokenPenalty").sort((a: any, b: any) => b[1] - a[1]).map(([key, value]: any) => <div key={key}><span>{human(key)}</span><i><i style={{ width: `${Math.min(100, value * 350)}%` }}/></i><b>{value.toFixed(3)}</b></div>)}</div><h3>Invalidated when</h3><ul className="keys">{item.invalidationKeys.map((key: any) => <li key={`${key.kind}:${key.key}`}><span>{key.kind}</span>{key.key}{key.expected ? ` ≠ ${short(key.expected)}` : " changes"}</li>)}</ul></aside>; }

function Routing({ data, runtimeEvidence }: { data: Replay; runtimeEvidence: any }) { const route = data.route; const risk = data.task.risk; return <section className="workspace"><PageIntro eyebrow="Model-routing timeline" title="Recommendation, request, and runtime truth never collapse into one label." body="This replay records a policy recommendation only. The separate recorded App Server panel is real runtime evidence and remains requested-unconfirmed unless a reroute/effective event exists."/><div className="routing-grid"><section className="panel route-features"><p className="eyebrow">Task features</p><h2>{human(route.phase)}</h2>{Object.entries(risk).map(([key, value]: any) => <div key={key}><span>{human(key)}</span><b>{value.toFixed(2)}</b></div>)}</section><section className="panel catalog"><p className="eyebrow">Policy catalog example</p><h2>{route.availableModels?.length ?? 0} non-runtime examples</h2>{route.availableModels?.map((model: any) => <div key={model.id}><b>{model.displayName ?? model.id}</b><span>{model.supportedReasoningEfforts.join(" · ")}</span></div>)}</section><section className="panel decision"><p className="eyebrow">Selected policy route</p><h2>{route.recommended.model}</h2><dl><Row label="Reasoning effort" value={route.recommended.reasoningEffort}/><Row label="Decision confidence" value={`${Math.round(route.confidence * 100)}%`}/><Row label="Fallback" value={`${route.fallback.model} / ${route.fallback.reasoningEffort}`}/><Row label="Budget implication" value={route.budgetImplication}/></dl></section></div>
    <section className="route-track"><RouteStep label="Recommended" value={`${route.recommended.model} / ${route.recommended.reasoningEffort}`} kind="estimate" state="planned"/><span>→</span><RouteStep label="Requested" value={route.requested ? `${route.requested.model} / ${route.requested.reasoningEffort}` : "Not observed"} kind={route.requested ? "measured" : "unavailable"} state={route.requested ? "active" : "inactive"}/><span>→</span><RouteStep label="Effective runtime" value={route.effective?.model ?? "Not observed"} kind={route.effective ? "measured" : "unavailable"} state={route.effective ? "completed" : "inactive"}/><span>→</span><RouteStep label="Result" value={route.result ?? "Not observed"} kind="unavailable" state="inactive"/></section>
    <div className="route-detail"><section><h3>Decision explanation</h3><ul>{route.reasons.map((reason: string) => <li key={reason}>{reason}</li>)}</ul></section><section><h3>Escalate when</h3><ul>{route.escalationConditions.map((reason: string) => <li key={reason}>{reason}</li>)}</ul></section><section><h3>Runtime measures</h3><dl><Row label="Token usage" value={fmt(route.tokenUsage)}/><Row label="Latency" value={route.latencyMs === null ? "Unavailable" : `${route.latencyMs} ms`}/><Row label="Reroutes" value={route.runtimeEvents?.length ? String(route.runtimeEvents.length) : "None observed"}/></dl></section><section className="review-panel"><h3>Independent reviewer</h3><TruthPill kind={data.review.passed ? "success" : "unavailable"}>{data.review.passed ? "verified" : "not observed"}</TruthPill><dl><Row label="Review state" value={data.review.passed === null ? "Unavailable in replay" : data.review.passed ? "Passed" : "Findings recorded"}/><Row label="Review thread" value={data.review.threadId ?? "Not observed"}/></dl></section></div>
    <section className="runtime-proof panel"><div><p className="eyebrow">{runtimeEvidence?.label ?? "Recorded App Server evidence"}</p><h2>{runtimeEvidence?.available ? "A real routed turn is retained." : "No retained runtime artifact."}</h2></div>{runtimeEvidence?.available ? <dl><Row label="Recorded at" value={time(runtimeEvidence.recordedAt)}/><Row label="Live catalog" value={`${runtimeEvidence.catalogSize} models`}/><Row label="Requested route" value={`${runtimeEvidence.requested.model} / ${runtimeEvidence.requested.reasoningEffort}`}/><Row label="Runtime truth" value={runtimeEvidence.modelState}/><Row label="Turn result" value={runtimeEvidence.outcome}/><Row label="Observed tokens" value={runtimeEvidence.totalTokens}/></dl> : <p>Run <code>npm run judge:live</code> with authenticated Codex access. Replay remains available.</p>}</section></section>; }

const eventTone = (type: string) => type.includes("review") ? "review" : type.includes("invalid") || type.includes("stale") ? "warning" : type.includes("expand") || type.includes("evidence") ? "expansion" : type.includes("pass") || type.includes("verified") || type.includes("complete") ? "success" : "default";
function Timeline({ data }: { data: Replay }) { return <section className="workspace"><PageIntro eyebrow="Context timeline" title="Every consequential change in one evidence chain." body="Capsules are immutable. Expansion creates a child; source changes invalidate rather than rewrite history."/><ol className="timeline">{data.timeline.map((event: any, index: number) => <li className={`timeline-event ${eventTone(event.type)}`} key={`${event.type}:${index}`}><span>{String(index + 1).padStart(2, "0")}</span><div><p>{event.type}</p><b>{event.detail}</b><small>{new Date(event.at).toLocaleTimeString()}</small></div></li>)}</ol></section>; }

const metricLabels: Record<string, string> = { taskSuccess: "Task success", testsPassed: "Tests passed", threadTokens: "Observed thread tokens", filesOpened: "Observable files opened", repeatedReads: "Observable repeated reads", toolCalls: "Tool calls", timeToFirstValidPatchMs: "Time to first valid patch", totalLatencyMs: "Total latency", unnecessaryChangedLines: "Unnecessary changed lines", reviewerFindings: "Reviewer findings", staleContextMistakes: "Stale-context mistakes", contextExpansionCount: "Context expansions" };
function Comparison({ data, benchmark }: { data: Replay; benchmark: Benchmark | null }) {
  const fair = benchmark?.comparisons?.find((item: any) => item.fairness?.passed); if (fair) return <section className="workspace"><PageIntro eyebrow="Baseline comparison / measured" title="A fair pair is available." body={`Task ${fair.taskId}; experiment ${fair.experiment}.`}/><ComparisonOutcomes outcomes={fair.outcomes}/><ComparisonHeader/><ComparisonTable metrics={fair.metrics}/></section>;
  return <section className="workspace"><PageIntro eyebrow="Baseline comparison / unavailable" title="Correctness first. Missing data stays missing." body="The harness is ready, but no complete fair baseline/Kerno pair is checked in."/><ComparisonHeader/><div className="comparison-table">{Object.entries(data.metrics).map(([key, value]) => <div key={key}><span>{metricLabels[key] ?? human(key)}</span><strong>Not recorded</strong><strong>{fmt(value)}</strong></div>)}</div><p className="disclosure">This replay proves the deterministic context loop, not a Codex-versus-Kerno performance claim. The product will display measured comparison data only after both fair conditions are retained.</p></section>;
}
function ComparisonHeader() { return <div className="comparison-head"><span>Metric</span><b><i className="series-key baseline" aria-hidden="true"/>Plain Codex baseline</b><b><i className="series-key kerno" aria-hidden="true"/>Kerno</b></div>; }
function ComparisonOutcomes({ outcomes }: { outcomes: any }) { return <section className="comparison-outcomes panel"><div><p className="eyebrow">Correctness first</p><h2>Pinned outcomes</h2></div><dl><Row label="Plain Codex" value={outcomes?.baseline ? `${outcomes.baseline.finalStatus}; tests ${outcomes.baseline.testsPassed ? "passed" : "failed"}; review ${outcomes.baseline.reviewStatus}` : "Unavailable"}/><Row label="Kerno" value={outcomes?.kerno ? `${outcomes.kerno.finalStatus}; tests ${outcomes.kerno.testsPassed ? "passed" : "failed"}; review ${outcomes.kerno.reviewStatus}` : "Unavailable"}/></dl></section>; }
function ComparisonTable({ metrics }: { metrics: Record<string, any> }) { return <div className="comparison-table measured-table">{Object.entries(metrics).map(([key, value]) => <div key={key}><span>{human(key)}</span><strong>{fmt(value.baseline)}</strong><strong>{fmt(value.kerno)}</strong></div>)}</div>; }

function Limits({ data, benchmark }: { data: Replay; benchmark: Benchmark | null }) { const fairPair = Boolean(benchmark?.comparisons?.some((item: any) => item.fairness?.passed)); const groups = [{ label: "Measured", kind: "measured", items: ["Zero unchanged files reparsed in the deterministic replay", "Initial and child capsule sizes", "Failing then passing pinned tests", "Source-hash invalidation", fairPair ? "One fair recorded App Server pair with independent review" : "No verified-fair recorded App Server pair"] }, { label: "Estimated", kind: "estimate", items: ["Capsule token counts use characters ÷ 4", "Context-value signals are deterministic policy scores"] }, { label: "Experimental", kind: "experimental", items: ["Phase-routing policy"] }, { label: "Unavailable", kind: "unavailable", items: ["Outcome usefulness learning is not implemented", "Effective runtime model for the recorded pair", "Independent review in the deterministic replay", "Unnecessary changed-line count", "Exact monetary cost"] }]; return <section className="workspace"><PageIntro eyebrow="Limitations and confidence" title="Claims bounded by their evidence." body="Replay, live, measured, estimated, experimental, unavailable, and unsupported states remain visibly distinct."/><div className="limit-ledger">{groups.map((group) => <section key={group.label}><TruthPill kind={group.kind}>{group.kind}</TruthPill><h2>{group.label}</h2><ul>{group.items.map((item) => <li key={item}>{item}</li>)}</ul></section>)}</div><section className="platforms"><h3>Platform status</h3><p><b>Tested:</b> macOS · Node 22.13. <b>CI configured:</b> macOS/Linux · Node 22/24. <b>Unsupported claim:</b> Windows has not been validated.</p></section><p className="artifact">Replay artifact SHA-256<br/><code>{data.artifactHash}</code></p></section>; }

function Outcome({ data }: { data: Replay }) { return <div className="outcome"><span>Recorded outcome</span><strong>{data.tests.after.passed ? "3 tests passed" : "Failed"}</strong><small>Independent review {data.review.passed === null ? "not observed" : data.review.passed ? "passed" : "failed"}</small></div>; }
function Metric({ n, label }: { n: unknown; label: string }) { return <div className="metric"><strong>{fmt(n)}</strong><span>{label}</span></div>; }
function Row({ label, value }: { label: string; value: unknown }) { return <div><dt>{label}</dt><dd>{fmt(value)}</dd></div>; }
function PageIntro({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) { return <header className="page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{body}</p></header>; }
function TruthPill({ kind, children }: { kind: string; children: React.ReactNode }) { return <span className={`truth-pill ${kind}`}>{children}</span>; }
function RouteStep({ label, value, kind, state }: { label: string; value: string; kind: string; state: "planned" | "active" | "completed" | "review" | "inactive" }) { return <div className={`route-${state}`}><TruthPill kind={kind}>{kind}</TruthPill><p>{label}</p><strong>{value}</strong></div>; }

createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
